### ISSUE TITLE
No power for OTG on i9195

### ISSUE THREAD

**Issue by WiggleWizard** [F4k/f4ktion_kernel#1]
I recently flashed your kernel on top of CM as I am using the phone in a project that needs external hardware to communicate with the phone however I am not getting any power from the phone. I believe I am running 2.3.1 (f4ktion_lp_2.3.1-eur_lte). Is there an update that provides OTG power to hardware without the need for an external power supply or is it yet to be implemented?

**Comment by F4k** [comment]
Only with a OTG Y cable, there's no update or fix yet.
